[general]
operator = "operatore1"
report_folder_path = "report"
execution_mode = "simulated"

[small_tube.test.gamma]
acquisition_time_sec = 100
max_sensitivity_deviation_percent = 5

[large_tube.test.gamma]
acquisition_time_sec = 100
max_sensitivity_deviation_percent = 5

[small_tube.test.starting_voltage]
voltage_steps = 10
min_detected_events = 6
step_acquisition_time_sec = 15
min_voltage = 5
max_voltage = 10
hv_increment_per_step = 10

[large_tube.test.starting_voltage]
voltage_steps = 10
min_detected_events = 6
step_acquisition_time_sec = 15
min_voltage = 5
max_voltage = 10
hv_increment_per_step = 10